-- CreateEnum
CREATE TYPE "EmploymentStatus" AS ENUM ('ACTIVE', 'RESIGNED', 'TERMINATED');

-- CreateEnum
CREATE TYPE "PayrollRunStatus" AS ENUM ('DRAFT', 'FINALIZED');

-- CreateEnum
CREATE TYPE "PayslipLineKind" AS ENUM ('EARNING', 'WAGE_DEDUCTION', 'NET_DEDUCTION');

-- CreateEnum
CREATE TYPE "StatutoryBandType" AS ENUM ('SOCSO', 'EIS');

-- CreateEnum
CREATE TYPE "StatutoryBandSource" AS ENUM ('GENERATED', 'MANUAL');

-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE 'STAFF';

-- CreateTable
CREATE TABLE "Employee" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "employeeCode" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "designation" TEXT NOT NULL,
    "department" TEXT,
    "nationality" TEXT,
    "gender" TEXT,
    "nricOrPassport" TEXT NOT NULL,
    "epfNumber" TEXT,
    "socsoNumber" TEXT,
    "pcbNumber" TEXT,
    "email" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "addressLine1" TEXT,
    "addressLine2" TEXT,
    "city" TEXT,
    "postcode" TEXT,
    "state" TEXT,
    "country" TEXT,
    "bankName" TEXT NOT NULL,
    "accountNumber" TEXT NOT NULL,
    "accountHolderName" TEXT,
    "status" "EmploymentStatus" NOT NULL DEFAULT 'ACTIVE',
    "hiredOn" TIMESTAMP(3) NOT NULL,
    "endedOn" TIMESTAMP(3),
    "epfEnabled" BOOLEAN NOT NULL DEFAULT true,
    "socsoEnabled" BOOLEAN NOT NULL DEFAULT true,
    "eisEnabled" BOOLEAN NOT NULL DEFAULT true,
    "epfEmployeeRateOverride" DECIMAL(5,2),
    "epfEmployerRateOverride" DECIMAL(5,2),
    "monthlyZakat" DECIMAL(14,2),
    "taxResident" BOOLEAN NOT NULL DEFAULT true,
    "taxWorkerCategory" TEXT DEFAULT 'Normal Worker',
    "taxMaritalStatus" TEXT,
    "taxDependents" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Employee_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SalaryRecord" (
    "id" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "monthlySalary" DECIMAL(14,2) NOT NULL,
    "effectiveFrom" TIMESTAMP(3) NOT NULL,
    "reason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SalaryRecord_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PayrollRun" (
    "id" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "month" INTEGER NOT NULL,
    "status" "PayrollRunStatus" NOT NULL DEFAULT 'DRAFT',
    "issuedOn" TIMESTAMP(3),
    "finalizedAt" TIMESTAMP(3),
    "paymentStatus" "PaymentStatus" NOT NULL DEFAULT 'UNPAID',
    "paidAt" TIMESTAMP(3),
    "paymentReference" TEXT,
    "rateSnapshot" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PayrollRun_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Payslip" (
    "id" TEXT NOT NULL,
    "runId" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "payslipNumber" TEXT NOT NULL,
    "employeeName" TEXT NOT NULL,
    "designation" TEXT NOT NULL,
    "department" TEXT,
    "nationality" TEXT,
    "gender" TEXT,
    "nricOrPassport" TEXT NOT NULL,
    "epfNumber" TEXT,
    "socsoNumber" TEXT,
    "pcbNumber" TEXT,
    "grossPay" DECIMAL(14,2) NOT NULL,
    "taxablePay" DECIMAL(14,2) NOT NULL,
    "epfBase" DECIMAL(14,2) NOT NULL,
    "socsoBase" DECIMAL(14,2) NOT NULL,
    "epfEmployee" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "epfEmployer" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "socsoEmployee" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "socsoEmployer" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "eisEmployee" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "eisEmployer" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "zakat" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "pcb" DECIMAL(14,2),
    "hrdfEmployer" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "totalEmployeeDeductions" DECIMAL(14,2) NOT NULL,
    "totalEmployerCost" DECIMAL(14,2) NOT NULL,
    "netPay" DECIMAL(14,2) NOT NULL,
    "proratedDays" INTEGER,
    "daysInMonth" INTEGER,
    "pdfPath" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Payslip_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PayslipLine" (
    "id" TEXT NOT NULL,
    "payslipId" TEXT NOT NULL,
    "kind" "PayslipLineKind" NOT NULL,
    "label" TEXT NOT NULL,
    "units" DECIMAL(10,2),
    "rate" DECIMAL(14,2),
    "amount" DECIMAL(14,2) NOT NULL,
    "taxable" BOOLEAN NOT NULL DEFAULT true,
    "epfApplicable" BOOLEAN NOT NULL DEFAULT true,
    "socsoApplicable" BOOLEAN NOT NULL DEFAULT true,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "PayslipLine_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "StatutoryBand" (
    "id" TEXT NOT NULL,
    "type" "StatutoryBandType" NOT NULL,
    "wageFrom" DECIMAL(14,2) NOT NULL,
    "wageTo" DECIMAL(14,2) NOT NULL,
    "employeeAmount" DECIMAL(14,2) NOT NULL,
    "employerAmount" DECIMAL(14,2) NOT NULL,
    "source" "StatutoryBandSource" NOT NULL DEFAULT 'GENERATED',

    CONSTRAINT "StatutoryBand_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PayrollSettings" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "employeeCodePrefix" TEXT NOT NULL DEFAULT 'G6-EMP-',
    "businessRegNumber" TEXT,
    "epfEmployerNumber" TEXT,
    "socsoEmployerNumber" TEXT,
    "lhdnEmployerNumber" TEXT,
    "epfEmployeeRate" DECIMAL(5,2) NOT NULL DEFAULT 11.00,
    "epfEmployerRate" DECIMAL(5,2) NOT NULL DEFAULT 12.00,
    "epfEmployerRateBelowThreshold" DECIMAL(5,2) NOT NULL DEFAULT 13.00,
    "epfEmployerThreshold" DECIMAL(14,2) NOT NULL DEFAULT 5000.00,
    "socsoEmployeeRate" DECIMAL(5,3) NOT NULL DEFAULT 0.500,
    "socsoEmployerRate" DECIMAL(5,3) NOT NULL DEFAULT 1.750,
    "socsoWageCeiling" DECIMAL(14,2) NOT NULL DEFAULT 6000.00,
    "socsoBandWidth" DECIMAL(14,2) NOT NULL DEFAULT 100.00,
    "eisEmployeeRate" DECIMAL(5,3) NOT NULL DEFAULT 0.200,
    "eisEmployerRate" DECIMAL(5,3) NOT NULL DEFAULT 0.200,
    "eisWageCeiling" DECIMAL(14,2) NOT NULL DEFAULT 6000.00,
    "eisBandWidth" DECIMAL(14,2) NOT NULL DEFAULT 100.00,
    "hrdfEnabled" BOOLEAN NOT NULL DEFAULT false,
    "hrdfRate" DECIMAL(5,2) NOT NULL DEFAULT 1.00,
    "payslipLogoUrl" TEXT,
    "accentColor" TEXT NOT NULL DEFAULT '#18181b',
    "showEmployerContributions" BOOLEAN NOT NULL DEFAULT true,
    "showHrdfColumn" BOOLEAN NOT NULL DEFAULT false,
    "showZakatColumn" BOOLEAN NOT NULL DEFAULT true,
    "epfFootnote" TEXT,
    "payslipFooterText" TEXT,
    "bandsGeneratedAt" TIMESTAMP(3),
    "bandsVerifiedAt" TIMESTAMP(3),
    "bandsVerifiedBy" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PayrollSettings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Employee_userId_key" ON "Employee"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "Employee_employeeCode_key" ON "Employee"("employeeCode");

-- CreateIndex
CREATE INDEX "Employee_status_idx" ON "Employee"("status");

-- CreateIndex
CREATE INDEX "SalaryRecord_employeeId_effectiveFrom_idx" ON "SalaryRecord"("employeeId", "effectiveFrom");

-- CreateIndex
CREATE UNIQUE INDEX "PayrollRun_year_month_key" ON "PayrollRun"("year", "month");

-- CreateIndex
CREATE UNIQUE INDEX "Payslip_payslipNumber_key" ON "Payslip"("payslipNumber");

-- CreateIndex
CREATE INDEX "Payslip_employeeId_idx" ON "Payslip"("employeeId");

-- CreateIndex
CREATE UNIQUE INDEX "Payslip_runId_employeeId_key" ON "Payslip"("runId", "employeeId");

-- CreateIndex
CREATE INDEX "PayslipLine_payslipId_idx" ON "PayslipLine"("payslipId");

-- CreateIndex
CREATE INDEX "StatutoryBand_type_idx" ON "StatutoryBand"("type");

-- CreateIndex
CREATE UNIQUE INDEX "StatutoryBand_type_wageFrom_key" ON "StatutoryBand"("type", "wageFrom");

-- AddForeignKey
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SalaryRecord" ADD CONSTRAINT "SalaryRecord_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payslip" ADD CONSTRAINT "Payslip_runId_fkey" FOREIGN KEY ("runId") REFERENCES "PayrollRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payslip" ADD CONSTRAINT "Payslip_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PayslipLine" ADD CONSTRAINT "PayslipLine_payslipId_fkey" FOREIGN KEY ("payslipId") REFERENCES "Payslip"("id") ON DELETE CASCADE ON UPDATE CASCADE;
