import { notFound, redirect } from "next/navigation";
import { requireAdmin } from "@/lib/currentUser";
import { AUTO_SALARY_LABEL } from "@/lib/payroll/run";
import { prisma } from "@/lib/prisma";
import { formatMoney } from "@/lib/stats";
import { PayslipLinesEditor, type PayslipLineRow } from "../PayslipLinesEditor";

export default async function EditPayslipLinesPage({
  params,
}: {
  params: Promise<{ id: string; payslipId: string }>;
}) {
  await requireAdmin();
  const { id, payslipId } = await params;

  const payslip = await prisma.payslip.findUnique({
    where: { id: payslipId },
    include: { lines: { orderBy: { sortOrder: "asc" } }, run: true },
  });
  if (!payslip || payslip.runId !== id) notFound();
  if (payslip.run.status === "FINALIZED") redirect(`/admin/payroll/${id}`);

  const salaryLine = payslip.lines.find((line) => line.autoGenerated);
  const daysLabel =
    payslip.proratedDays !== null &&
    payslip.daysInMonth !== null &&
    payslip.proratedDays !== payslip.daysInMonth
      ? `${payslip.proratedDays}/${payslip.daysInMonth} days`
      : "Full month";

  const initialRows: PayslipLineRow[] = payslip.lines
    .filter((line) => !line.autoGenerated)
    .map((line) => ({
      kind: line.kind,
      label: line.label,
      units: line.units !== null ? String(line.units) : "",
      rate: line.rate !== null ? String(line.rate) : "",
      amount: String(line.amount),
      taxable: line.taxable,
      epfApplicable: line.epfApplicable,
      socsoApplicable: line.socsoApplicable,
    }));

  return (
    <div className="space-y-6">
      <h1 className="g6-page-title">
        {payslip.employeeName} — {payslip.payslipNumber}
      </h1>

      <div className="g6-panel space-y-3 p-4">
        <p className="text-[13px] font-semibold text-[#ece9f5]">Salary (read-only)</p>
        <dl className="grid grid-cols-1 gap-3 text-sm sm:grid-cols-3">
          <div>
            <dt className="text-[11px] uppercase tracking-wide text-[#8781a0]">Label</dt>
            <dd className="mt-0.5 font-medium">{salaryLine?.label ?? AUTO_SALARY_LABEL}</dd>
          </div>
          <div>
            <dt className="text-[11px] uppercase tracking-wide text-[#8781a0]">Days</dt>
            <dd className="mt-0.5 font-medium">{daysLabel}</dd>
          </div>
          <div>
            <dt className="text-[11px] uppercase tracking-wide text-[#8781a0]">Amount</dt>
            <dd className="mt-0.5 font-mono-g6 font-medium">
              {formatMoney(Number(salaryLine?.amount ?? 0))}
            </dd>
          </div>
        </dl>
        <p className="text-[12px] text-[#8781a0]">
          The salary line is derived from the salary timeline and this month&apos;s dates. To adjust pay, add an
          arrears earning or an unpaid-leave deduction below.
        </p>
      </div>

      <PayslipLinesEditor
        payslipId={payslipId}
        initialRows={initialRows}
        initialNotes={payslip.notes ?? ""}
      />
    </div>
  );
}
