import "server-only";
import type { Employee, PayslipLineKind, Prisma, SalaryRecord } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { computePayslip } from "./calc";
import { formatPayslipNumber } from "./payslipNumber";
import { prorateSalaryForMonth } from "./proration";
import { loadRateConfig } from "./rates";
import type { LineInput, PayslipCalcOutput, RateConfig } from "./types";

/** The label on the salary line the generator creates. */
export const AUTO_SALARY_LABEL = "Salary";

/** Maps engine output onto the Payslip scalar columns. */
export function payslipMoneyFields(computed: PayslipCalcOutput) {
  return {
    grossPay: computed.grossPay,
    taxablePay: computed.taxablePay,
    epfBase: computed.epfBase,
    socsoBase: computed.socsoBase,
    epfEmployee: computed.epfEmployee,
    epfEmployer: computed.epfEmployer,
    socsoEmployee: computed.socsoEmployee,
    socsoEmployer: computed.socsoEmployer,
    eisEmployee: computed.eisEmployee,
    eisEmployer: computed.eisEmployer,
    zakat: computed.zakat,
    hrdfEmployer: computed.hrdfEmployer,
    totalEmployeeDeductions: computed.totalEmployeeDeductions,
    totalEmployerCost: computed.totalEmployerCost,
    netPay: computed.netPay,
  };
}

/** Strips stored lines down to what the pure engine needs, coercing Decimals. */
export function toCalcLines(
  lines: {
    kind: PayslipLineKind;
    amount: Prisma.Decimal | number;
    taxable: boolean;
    epfApplicable: boolean;
    socsoApplicable: boolean;
  }[]
): LineInput[] {
  return lines.map((line) => ({
    kind: line.kind,
    amount: Number(line.amount),
    taxable: line.taxable,
    epfApplicable: line.epfApplicable,
    socsoApplicable: line.socsoApplicable,
  }));
}

/** The statutory facts the engine needs about an employee. */
function calcFacts(employee: Employee, pcb: number) {
  return {
    epfEnabled: employee.epfEnabled,
    socsoEnabled: employee.socsoEnabled,
    eisEnabled: employee.eisEnabled,
    epfEmployeeRateOverride:
      employee.epfEmployeeRateOverride === null ? null : Number(employee.epfEmployeeRateOverride),
    epfEmployerRateOverride:
      employee.epfEmployerRateOverride === null ? null : Number(employee.epfEmployerRateOverride),
    monthlyZakat: employee.monthlyZakat === null ? 0 : Number(employee.monthlyZakat),
    pcb,
  };
}

/** The employee facts copied onto the payslip so it survives later profile edits. */
function snapshotEmployeeFacts(employee: Employee) {
  return {
    employeeName: employee.fullName,
    designation: employee.designation,
    department: employee.department,
    nationality: employee.nationality,
    gender: employee.gender,
    nricOrPassport: employee.nricOrPassport,
    epfNumber: employee.epfNumber,
    socsoNumber: employee.socsoNumber,
    pcbNumber: employee.pcbNumber,
  };
}

/**
 * Everyone employed on ANY day of the month, so mid-month joiners and leavers
 * are included and prorated. Employment status is irrelevant here — the dates
 * decide. Someone terminated last year is excluded by the endedOn bound.
 */
async function employeesForMonth(year: number, month: number) {
  const monthStart = new Date(Date.UTC(year, month - 1, 1));
  const monthEnd = new Date(Date.UTC(year, month, 0));

  return prisma.employee.findMany({
    where: {
      hiredOn: { lte: monthEnd },
      OR: [{ endedOn: null }, { endedOn: { gte: monthStart } }],
    },
    include: { salaryRecords: true },
    orderBy: { employeeCode: "asc" },
  });
}

/**
 * Creates or refreshes one draft payslip.
 *
 * Refresh semantics matter: re-generating a draft run rebuilds only the
 * auto-generated salary line and leaves every hand-added allowance, arrears or
 * loan line in place, along with whatever PCB the admin has already entered.
 * Wiping those would make re-generating a destructive act.
 */
async function draftPayslip(params: {
  runId: string;
  employee: Employee & { salaryRecords: SalaryRecord[] };
  config: RateConfig;
  year: number;
  month: number;
}) {
  const { runId, employee, config, year, month } = params;

  const prorated = prorateSalaryForMonth({
    year,
    month,
    salaryRecords: employee.salaryRecords.map((record) => ({
      monthlySalary: Number(record.monthlySalary),
      effectiveFrom: record.effectiveFrom,
    })),
    hiredOn: employee.hiredOn,
    endedOn: employee.endedOn,
  });

  const existing = await prisma.payslip.findUnique({
    where: { runId_employeeId: { runId, employeeId: employee.id } },
    include: { lines: true },
  });

  const manualLines = existing?.lines.filter((line) => !line.autoGenerated) ?? [];
  const pcb = existing?.pcb === null || existing === null ? 0 : Number(existing.pcb);

  const isPartialMonth = prorated.proratedDays < prorated.daysInMonth;
  const salaryLine = {
    kind: "EARNING" as const,
    label: AUTO_SALARY_LABEL,
    // Units are shown only for a partial month, where "16 / 31 days" is the
    // explanation the employee needs. A full month has no interesting units.
    units: isPartialMonth ? prorated.proratedDays : null,
    rate: null,
    amount: prorated.amount,
    taxable: true,
    epfApplicable: true,
    socsoApplicable: true,
    autoGenerated: true,
    sortOrder: 0,
  };

  const computed = computePayslip({
    lines: toCalcLines([salaryLine, ...manualLines]),
    employee: calcFacts(employee, pcb),
    config,
  });

  const shared = {
    ...snapshotEmployeeFacts(employee),
    ...payslipMoneyFields(computed),
    proratedDays: prorated.proratedDays,
    daysInMonth: prorated.daysInMonth,
  };

  if (existing) {
    await prisma.$transaction([
      prisma.payslipLine.deleteMany({ where: { payslipId: existing.id, autoGenerated: true } }),
      prisma.payslip.update({
        where: { id: existing.id },
        data: { ...shared, lines: { create: [salaryLine] } },
      }),
    ]);
    return;
  }

  await prisma.payslip.create({
    data: {
      runId,
      employeeId: employee.id,
      payslipNumber: formatPayslipNumber(year, month, employee.employeeCode),
      pcb: null,
      ...shared,
      lines: { create: [salaryLine] },
    },
  });
}

/**
 * Drafts (or refreshes) the payroll run for a month.
 *
 * Idempotent: the unique constraint on (year, month) means a month can only
 * ever have one run, and re-running against a DRAFT refreshes it. A FINALIZED
 * run is refused outright — that is the whole point of finalizing.
 */
export async function generatePayrollRun(year: number, month: number) {
  const existing = await prisma.payrollRun.findUnique({ where: { year_month: { year, month } } });

  if (existing?.status === "FINALIZED") {
    throw new Error("This payroll run has been finalized and cannot be regenerated.");
  }

  const run = existing ?? (await prisma.payrollRun.create({ data: { year, month } }));
  const config = await loadRateConfig();
  const employees = await employeesForMonth(year, month);

  const draftGuard = await prisma.payrollRun.updateMany({
    where: { id: run.id, status: "DRAFT" },
    data: { updatedAt: new Date() },
  });
  if (draftGuard.count === 0) {
    throw new Error("This payroll run has been finalized and cannot be regenerated.");
  }

  const eligibleIds = employees.map((employee) => employee.id);
  await prisma.payslip.deleteMany({
    where: {
      runId: run.id,
      ...(eligibleIds.length > 0 ? { employeeId: { notIn: eligibleIds } } : {}),
    },
  });

  for (const employee of employees) {
    await draftPayslip({ runId: run.id, employee, config, year, month });
  }

  return { runId: run.id, drafted: employees.length };
}

/**
 * Recomputes one draft payslip from its current lines and PCB. Called after an
 * admin edits lines or enters PCB, so the stored figures never lag the lines.
 */
export async function recomputePayslip(payslipId: string): Promise<void> {
  const payslip = await prisma.payslip.findUniqueOrThrow({
    where: { id: payslipId },
    include: { lines: true, employee: true, run: true },
  });

  if (payslip.run.status === "FINALIZED") {
    throw new Error("This payslip belongs to a finalized run and cannot be recomputed.");
  }

  const config = await loadRateConfig();
  const computed = computePayslip({
    lines: toCalcLines(payslip.lines),
    employee: calcFacts(payslip.employee, payslip.pcb === null ? 0 : Number(payslip.pcb)),
    config,
  });

  const updated = await prisma.payslip.updateMany({
    where: { id: payslipId, run: { status: "DRAFT" } },
    data: payslipMoneyFields(computed),
  });
  if (updated.count === 0) {
    throw new Error("This payslip belongs to a finalized run and cannot be recomputed.");
  }
}
