import "server-only";
import type { Employee, PayslipLineKind, Prisma, SalaryRecord } from "@prisma/client";
import { renderPayslipPdf } from "@/lib/pdf/render";
import { prisma } from "@/lib/prisma";
import { savePdf } from "@/lib/storage";
import { computePayslip } from "./calc";
import { buildPayslipPdfData } from "./payslipPdf";
import { formatPayslipNumber } from "./payslipNumber";
import { prorateSalaryForMonth } from "./proration";
import { loadRateConfig } from "./rates";
import type { LineInput, PayslipCalcOutput, RateConfig } from "./types";

/** The label on the salary line the generator creates. */
export const AUTO_SALARY_LABEL = "Salary";

/** Maps engine output onto the Payslip scalar columns. */
export function payslipMoneyFields(computed: PayslipCalcOutput) {
  return {
    grossPay: computed.grossPay,
    taxablePay: computed.taxablePay,
    epfBase: computed.epfBase,
    socsoBase: computed.socsoBase,
    epfEmployee: computed.epfEmployee,
    epfEmployer: computed.epfEmployer,
    socsoEmployee: computed.socsoEmployee,
    socsoEmployer: computed.socsoEmployer,
    eisEmployee: computed.eisEmployee,
    eisEmployer: computed.eisEmployer,
    zakat: computed.zakat,
    hrdfEmployer: computed.hrdfEmployer,
    totalEmployeeDeductions: computed.totalEmployeeDeductions,
    totalEmployerCost: computed.totalEmployerCost,
    netPay: computed.netPay,
  };
}

/** Strips stored lines down to what the pure engine needs, coercing Decimals. */
export function toCalcLines(
  lines: {
    kind: PayslipLineKind;
    amount: Prisma.Decimal | number;
    taxable: boolean;
    epfApplicable: boolean;
    socsoApplicable: boolean;
  }[]
): LineInput[] {
  return lines.map((line) => ({
    kind: line.kind,
    amount: Number(line.amount),
    taxable: line.taxable,
    epfApplicable: line.epfApplicable,
    socsoApplicable: line.socsoApplicable,
  }));
}

/** The statutory facts the engine needs about an employee. */
function calcFacts(employee: Employee, pcb: number) {
  return {
    epfEnabled: employee.epfEnabled,
    socsoEnabled: employee.socsoEnabled,
    eisEnabled: employee.eisEnabled,
    epfEmployeeRateOverride:
      employee.epfEmployeeRateOverride === null ? null : Number(employee.epfEmployeeRateOverride),
    epfEmployerRateOverride:
      employee.epfEmployerRateOverride === null ? null : Number(employee.epfEmployerRateOverride),
    monthlyZakat: employee.monthlyZakat === null ? 0 : Number(employee.monthlyZakat),
    pcb,
  };
}

/** The employee facts copied onto the payslip so it survives later profile edits. */
function snapshotEmployeeFacts(employee: Employee) {
  return {
    employeeName: employee.fullName,
    designation: employee.designation,
    department: employee.department,
    nationality: employee.nationality,
    gender: employee.gender,
    nricOrPassport: employee.nricOrPassport,
    epfNumber: employee.epfNumber,
    socsoNumber: employee.socsoNumber,
    pcbNumber: employee.pcbNumber,
  };
}

/**
 * Everyone employed on ANY day of the month, so mid-month joiners and leavers
 * are included and prorated. Employment status is irrelevant here — the dates
 * decide. Someone terminated last year is excluded by the endedOn bound.
 */
async function employeesForMonth(year: number, month: number) {
  const monthStart = new Date(Date.UTC(year, month - 1, 1));
  const monthEnd = new Date(Date.UTC(year, month, 0));

  return prisma.employee.findMany({
    where: {
      hiredOn: { lte: monthEnd },
      OR: [{ endedOn: null }, { endedOn: { gte: monthStart } }],
    },
    include: { salaryRecords: true },
    orderBy: { employeeCode: "asc" },
  });
}

/**
 * Creates or refreshes one draft payslip.
 *
 * Refresh semantics matter: re-generating a draft run rebuilds only the
 * auto-generated salary line and leaves every hand-added allowance, arrears or
 * loan line in place, along with whatever PCB the admin has already entered.
 * Wiping those would make re-generating a destructive act.
 */
async function draftPayslip(params: {
  runId: string;
  employee: Employee & { salaryRecords: SalaryRecord[] };
  config: RateConfig;
  year: number;
  month: number;
}) {
  const { runId, employee, config, year, month } = params;

  const prorated = prorateSalaryForMonth({
    year,
    month,
    salaryRecords: employee.salaryRecords.map((record) => ({
      monthlySalary: Number(record.monthlySalary),
      effectiveFrom: record.effectiveFrom,
    })),
    hiredOn: employee.hiredOn,
    endedOn: employee.endedOn,
  });

  const existing = await prisma.payslip.findUnique({
    where: { runId_employeeId: { runId, employeeId: employee.id } },
    include: { lines: true },
  });

  const manualLines = existing?.lines.filter((line) => !line.autoGenerated) ?? [];
  const pcb = existing?.pcb === null || existing === null ? 0 : Number(existing.pcb);

  const isPartialMonth = prorated.proratedDays < prorated.daysInMonth;
  const salaryLine = {
    kind: "EARNING" as const,
    label: AUTO_SALARY_LABEL,
    // Units are shown only for a partial month, where "16 / 31 days" is the
    // explanation the employee needs. A full month has no interesting units.
    units: isPartialMonth ? prorated.proratedDays : null,
    rate: null,
    amount: prorated.amount,
    taxable: true,
    epfApplicable: true,
    socsoApplicable: true,
    autoGenerated: true,
    sortOrder: 0,
  };

  const computed = computePayslip({
    lines: toCalcLines([salaryLine, ...manualLines]),
    employee: calcFacts(employee, pcb),
    config,
  });

  const shared = {
    ...snapshotEmployeeFacts(employee),
    ...payslipMoneyFields(computed),
    proratedDays: prorated.proratedDays,
    daysInMonth: prorated.daysInMonth,
  };

  if (existing) {
    await prisma.$transaction([
      prisma.payslipLine.deleteMany({ where: { payslipId: existing.id, autoGenerated: true } }),
      prisma.payslip.update({
        where: { id: existing.id },
        data: { ...shared, lines: { create: [salaryLine] } },
      }),
    ]);
    return;
  }

  await prisma.payslip.create({
    data: {
      runId,
      employeeId: employee.id,
      payslipNumber: formatPayslipNumber(year, month, employee.employeeCode),
      pcb: null,
      ...shared,
      lines: { create: [salaryLine] },
    },
  });
}

/**
 * Drafts (or refreshes) the payroll run for a month.
 *
 * Idempotent: the unique constraint on (year, month) means a month can only
 * ever have one run, and re-running against a DRAFT refreshes it. A FINALIZED
 * run is refused outright — that is the whole point of finalizing.
 */
export async function generatePayrollRun(year: number, month: number) {
  const existing = await prisma.payrollRun.findUnique({ where: { year_month: { year, month } } });

  if (existing?.status === "FINALIZED") {
    throw new Error("This payroll run has been finalized and cannot be regenerated.");
  }

  const run = existing ?? (await prisma.payrollRun.create({ data: { year, month } }));
  const config = await loadRateConfig();
  const employees = await employeesForMonth(year, month);

  const draftGuard = await prisma.payrollRun.updateMany({
    where: { id: run.id, status: "DRAFT" },
    data: { updatedAt: new Date() },
  });
  if (draftGuard.count === 0) {
    throw new Error("This payroll run has been finalized and cannot be regenerated.");
  }

  const eligibleIds = employees.map((employee) => employee.id);
  await prisma.payslip.deleteMany({
    where: {
      runId: run.id,
      ...(eligibleIds.length > 0 ? { employeeId: { notIn: eligibleIds } } : {}),
    },
  });

  for (const employee of employees) {
    await draftPayslip({ runId: run.id, employee, config, year, month });
  }

  return { runId: run.id, drafted: employees.length };
}

/**
 * Recomputes one draft payslip from its current lines and PCB. Called after an
 * admin edits lines or enters PCB, so the stored figures never lag the lines.
 */
export async function recomputePayslip(payslipId: string): Promise<void> {
  const payslip = await prisma.payslip.findUniqueOrThrow({
    where: { id: payslipId },
    include: { lines: true, employee: true, run: true },
  });

  if (payslip.run.status === "FINALIZED") {
    throw new Error("This payslip belongs to a finalized run and cannot be recomputed.");
  }

  const config = await loadRateConfig();
  const computed = computePayslip({
    lines: toCalcLines(payslip.lines),
    employee: calcFacts(payslip.employee, payslip.pcb === null ? 0 : Number(payslip.pcb)),
    config,
  });

  const updated = await prisma.payslip.updateMany({
    where: { id: payslipId, run: { status: "DRAFT" } },
    data: payslipMoneyFields(computed),
  });
  if (updated.count === 0) {
    throw new Error("This payslip belongs to a finalized run and cannot be recomputed.");
  }
}

export type FinalizeIssue = { payslipId: string; employeeName: string; message: string };

type PayrollRunDb = Pick<typeof prisma, "payrollRun">;

/**
 * Everything that must be true before a run can be issued.
 *
 * These guards are the reason the draft/finalize split exists. A payslip with a
 * negative net or a missing statutory number looks plausible and is wrong, and
 * once issued it cannot be quietly corrected.
 */
async function validateRunForFinalizeWithDb(db: PayrollRunDb, runId: string): Promise<FinalizeIssue[]> {
  const run = await db.payrollRun.findUniqueOrThrow({
    where: { id: runId },
    include: { payslips: { include: { employee: true } } },
  });

  if (run.status === "FINALIZED") {
    return [{ payslipId: "", employeeName: "", message: "This run has already been finalized." }];
  }

  if (run.payslips.length === 0) {
    return [{ payslipId: "", employeeName: "", message: "This run has no payslips. Generate it first." }];
  }

  const issues: FinalizeIssue[] = [];

  for (const payslip of run.payslips) {
    const add = (message: string) =>
      issues.push({ payslipId: payslip.id, employeeName: payslip.employeeName, message });

    if (payslip.pcb === null) {
      add("PCB has not been entered. Enter the LHDN figure, or 0.00 to confirm none is due.");
    }

    if (Number(payslip.netPay) < 0) {
      add(
        `Net pay is negative (${Number(payslip.netPay).toFixed(2)}). Deductions exceed pay — reduce a deduction before issuing.`
      );
    }

    if (payslip.employee.epfEnabled && !payslip.epfNumber) {
      add("EPF is enabled for this employee but no EPF number is on file.");
    }

    if (payslip.employee.socsoEnabled && !payslip.socsoNumber) {
      add("SOCSO is enabled for this employee but no SOCSO number is on file.");
    }
  }

  return issues;
}

export async function validateRunForFinalize(runId: string): Promise<FinalizeIssue[]> {
  return validateRunForFinalizeWithDb(prisma, runId);
}

/**
 * Locks the run, then renders the PDFs.
 *
 * The status flip and figure freeze happen in one transaction; rendering runs
 * afterwards, sequentially, following the same pattern as
 * createInvoiceSubmission in src/lib/invoice.ts. Rendering inside the
 * transaction would hold it open across N PDF renders against a 300s function
 * ceiling.
 *
 * The honest failure mode: if rendering dies partway, the run is locked with
 * some pdfPath still null. regenerateMissingPayslipPdfs covers that, and the
 * admin UI surfaces it. Locking first is the right trade — a locked run with a
 * missing PDF is recoverable, whereas an unlocked run whose PDFs have been
 * handed out is not.
 */
export async function finalizePayrollRun(runId: string) {
  const issues = await validateRunForFinalize(runId);
  if (issues.length > 0) return { ok: false as const, issues };

  const config = await loadRateConfig();
  const now = new Date();

  const lockResult = await prisma.$transaction(async (tx) => {
    const txIssues = await validateRunForFinalizeWithDb(tx, runId);
    if (txIssues.length > 0) {
      return { ok: false as const, issues: txIssues };
    }

    const updated = await tx.payrollRun.updateMany({
      where: { id: runId, status: "DRAFT" },
      data: {
        status: "FINALIZED",
        finalizedAt: now,
        issuedOn: now,
        rateSnapshot: config as unknown as Prisma.InputJsonValue,
      },
    });

    if (updated.count === 0) {
      return {
        ok: false as const,
        issues: [{ payslipId: "", employeeName: "", message: "This run has already been finalized." }],
      };
    }

    const payslips = await tx.payslip.findMany({ where: { runId }, select: { id: true } });
    return { ok: true as const, payslipIds: payslips.map((payslip) => payslip.id) };
  });

  if (!lockResult.ok) return lockResult;

  let rendered = 0;
  let failed = 0;

  for (const payslipId of lockResult.payslipIds) {
    try {
      await renderAndStorePayslipPdf(payslipId);
      rendered++;
    } catch {
      failed++;
    }
  }

  return { ok: true as const, rendered, failed };
}

async function renderAndStorePayslipPdf(payslipId: string): Promise<void> {
  const data = await buildPayslipPdfData(payslipId);
  const buffer = await renderPayslipPdf(data);

  const payslip = await prisma.payslip.findUniqueOrThrow({
    where: { id: payslipId },
    select: { payslipNumber: true, employeeId: true },
  });

  const url = await savePdf(buffer, `payslips/${payslip.employeeId}`, `${payslip.payslipNumber}.pdf`);
  await prisma.payslip.update({ where: { id: payslipId }, data: { pdfPath: url } });
}

/** Retries the payslips whose PDF never got written. Safe to run repeatedly. */
export async function regenerateMissingPayslipPdfs(runId: string): Promise<number> {
  const missing = await prisma.payslip.findMany({
    where: { runId, pdfPath: null },
    select: { id: true },
  });

  let repaired = 0;
  for (const payslip of missing) {
    try {
      await renderAndStorePayslipPdf(payslip.id);
      repaired++;
    } catch {
      // Left for the next attempt; the UI keeps showing the missing-PDF warning.
    }
  }
  return repaired;
}
